services:

  admin-backend:
    image: ghcr.io/andrepenteado/apadmin-backend
    container_name: admin-backend
    hostname: admin-backend
    environment:
      SPRING_PROFILES_ACTIVE: dev
      AUTHORIZATION_SERVER_URL: http://login:30000
    ports:
      - 30003:8080
    networks:
      - docker-host-network

  admin-frontend:
    image: ghcr.io/andrepenteado/apadmin-frontend
    container_name: admin-frontend
    hostname: admin-frontend
    ports:
      - 40003:80
    networks:
      - docker-host-network

networks:
  docker-host-network:
    external: true
