spring:
  datasource:
    url: jdbc:postgresql://dev.db.apcode.com.br/apadmin-dbname

  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: http://dev.login.apcode.com.br:30000

management:
  tracing:
    enabled: false
